"""Add due_date to borrowing

Revision ID: 79c17f163a9c
Revises: 474eba39a9f0
Create Date: 2025-10-25 17:28:22.584359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c17f163a9c'
down_revision: Union[str, Sequence[str], None] = '474eba39a9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowings', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrowings', 'due_date')
    # ### end Alembic commands ###
